env:
  global:
    - CC_TEST_REPORTER_ID=f5a226122f0661736323b9f1431103b20ee56788fa5bdda61bd5314b72d47892
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - PUBSUB_EMULATOR_HOST=localhost:8085
    - PUBSUB_PROJECT_ID=subserver-ci

language: ruby
cache:
  bundler: true
  directories:
    - "$HOME/google-cloud-sdk/"

rvm:
  - 2.3.7

install:
  # Install Google Cloud SDK or load it from cache
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud components install pubsub-emulator
  # Install Gems via Bundler
  - bundle install --deployment

before_script:
  # Start Cloud Pubsub Emulator
  - gcloud beta emulators pubsub start &
  - sleep 20 # Let emulator start on thread
  # Load Code Climate Test Coverage Reporter
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: 
  # Run RSpec Tests
  'bundle exec rspec ./spec'
after_script:
  # Report Coverage to CC 
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT