source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.3.7'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.0'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use Puma as the app server
gem 'puma', '~> 3.11'
# Use dotenv to load development env variables
gem 'dotenv-rails', require: 'dotenv/rails-now'

# Load Subserver from development path
gem 'subserver', :path => '..'
gem 'rspec'